version: '3.9'

services:
  next-app:
    container_name: reserv-voyage
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    environment:
      POSTGRES_ADDR: postgres
      POSTGRES_DATABASE: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - postgres
    volumes:
      - .:/app/next-app
    restart: always
    ports:
      - 3000:3000
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
